### ISSUE TITLE
Do not require message

### ISSUE THREAD

**Issue by pkristian** [franiglesias/versiontag#6]
it would be cool, if message will not be required.

**Comment by franiglesias** [comment]
I'll look into it. I've had problems trying to tag without message (the script failed).

**Comment by pkristian** [comment]
the problem is, that you after `major|minor|patch` you expect message.
since this package is new, i will suggest BC break: `versiontag major -m|--message "message"`
same like in `git commit`

**Comment by franiglesias** [comment]
The problem happened when the script tried to execute git tag without message. It failed when opening editor to add message. I've not looked yet how to tag with no message, so I force a message to be passed. I'm agree with the BC break. I'll take a look this night :-).

**Comment by pkristian** [comment]
i looked in docu: https://git-scm.com/docs/git-tag

it looks like it is problem with `git tag -a` which looks like require message
but unannotated tags are ignored by `git describle`, so what about to change to `git tag --list` for getting last tag?

**Comment by franiglesias** [comment]
I'm looking into that, but see issue #4 to discuss about the source of truth about versioning. Having the .semver file, I'm considering to use it instead of git tags (or have some kind of check to verify them. Not sure about that).

By the other hand, git tag --list has the problem that could be difficult to know which is the last tag.

**Comment by franiglesias** [comment]
I want to merge some fixes before implement this.
